[package]
name = "gpusorted_map"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = { version = "1.14", features = ["derive"] }
pollster = "0.3"
rand = "0.8"
wgpu = "0.20"

[[bench]]
name = "perf"
harness = false
